export const APP_LANGUAGE_STORAGE_KEY = "appLanguage";
export const APP_LANGUAGE_EVENT = "app-language-changed";

export type AppLanguage = "en" | "hi" | "mr";

const SUPPORTED_LANGUAGES: AppLanguage[] = ["en", "hi", "mr"];

export const LANGUAGE_OPTIONS: Array<{ code: AppLanguage; label: string }> = [
    { code: "en", label: "English" },
    { code: "hi", label: "Hindi" },
    { code: "mr", label: "Marathi" },
];

export function normalizeLanguage(value?: string | null): AppLanguage {
    const code = String(value || "en").trim().toLowerCase() as AppLanguage;
    return SUPPORTED_LANGUAGES.includes(code) ? code : "en";
}

function getLanguageStorageKeyForCurrentUser(): string {
    const role = String(localStorage.getItem("authRole") || "guest").trim().toLowerCase();
    const userId = String(localStorage.getItem("user_id") || "").trim();
    const email = String(localStorage.getItem("authEmail") || "").trim().toLowerCase();
    const phone = String(localStorage.getItem("authPhone") || "").replace(/\D+/g, "");

    // Prefer current login identity first so stale user_id from previous sessions
    // cannot leak language preference across accounts.
    const identity = email || phone || userId || "guest";
    return `lang_${role}_${identity}`;
}

export function getAppLanguage(): AppLanguage {
    const key = getLanguageStorageKeyForCurrentUser();
    return normalizeLanguage(localStorage.getItem(key));
}

export function setAppLanguage(language: string): AppLanguage {
    const normalized = normalizeLanguage(language);
    const key = getLanguageStorageKeyForCurrentUser();
    localStorage.setItem(key, normalized);
    window.dispatchEvent(
        new CustomEvent(APP_LANGUAGE_EVENT, {
            detail: { language: normalized, storageKey: key },
        })
    );
    return normalized;
}

const DICTIONARY: Record<AppLanguage, Record<string, string>> = {
    en: {
        settingsTitle: "Settings & Control Panel",
        securityConsole: "Security Console",
        settingsOverview: "Manage system behavior, alerts, language, and operations policy.",
        unsaved: "Unsaved",
        synced: "Synced",
        reset: "Reset",
        discardChanges: "Discard Changes",
        saveAll: "Save All",
        unsavedChangesDetected: "Unsaved changes detected",
        allSettingsSynced: "All settings are synchronized",
        sessionControl: "Session Control",
        sessionControlHint: "Sign out is managed only here for cleaner admin operations.",
        whatsappGuardAlerts: "WhatsApp Guard Alerts",
        whatsappGuardAlertsDesc: "Control WhatsApp alert delivery for on-duty guards.",
        aiPolicy: "AI Policy",
        aiPolicyDesc: "Tune AI sensitivity and dispatch cooldown for stable operations.",
        languageAndLocalization: "Language & Localization",
        languageAndLocalizationDesc: "Control interface and messaging language behavior across the platform.",
        dataAndMaintenance: "Data & Maintenance",
        dataMaintenanceAudit: "Data, Maintenance & Audit",
        dataMaintenanceAuditDesc: "Observe storage growth, retention policy, and critical operations logs.",
        languageSectionTitle: "Language",
        languageSectionDescription: "Choose the application language for dashboard and chat.",
        languageLabel: "Preferred Language",
        languageSaved: "Language updated. Chat and dashboard will use your selected language.",
        settingsSaved: "Settings saved.",
        settingsSaveFailed: "Failed to save settings.",
        notificationsTitle: "Notifications",
        notificationsDescription: "Configure how you receive alerts and notifications",
        smsAlertsTitle: "SMS Alerts to Admin",
        smsAlertsDescription: "Send text messages for critical threats",
        sirenTitle: "Siren Sound on Detection",
        sirenDescription: "Play alert sound when threat is detected",
        emailAlertsTitle: "Email Notifications",
        emailAlertsDescription: "Receive email updates for incidents",
        aiSensitivityTitle: "AI Sensitivity",
        aiSensitivityDescription: "Adjust detection accuracy threshold",
        detectionThresholdLabel: "Detection Threshold",
        moreAlerts: "More Alerts",
        fewerAlerts: "Fewer Alerts",
        currentSettingLabel: "Current Setting:",
        currentSettingDescription: "The AI will only trigger alerts when it's {threshold}% confident or higher. Lower values will increase sensitivity but may result in more false positives.",
        maintenanceTitle: "System Maintenance",
        maintenanceDescription: "Manage storage and system cleanup",
        clearFootageTitle: "Clear Old Footage",
        clearFootageDescription: "Remove recordings older than 30 days",
        clearNow: "Clear Now",
        clearFootageWarning: "This will permanently delete old footage to free up storage space. This action cannot be undone.",
        cancel: "Cancel",
        saveSettingsBtn: "Save Settings & Apply Detection Threshold",
        guardAssistant: "GuardGPT Assistant",
        commandCenter: "Security Command Center",
        askPlaceholder: "Type a security command or question...",
        emptyChatHint: "Ask for pending alerts, latest alert, guard count, or upload an image for AI analysis.",
        loadingSearch: "Just a second, I'm searching for you...",
        loadingAnalyze: "Wait a minute, analyzing the data...",
        loadingFind: "OK sir, I'm finding that for you...",
        loadingLogs: "Processing security logs...",
        dashboardFeed: "Live Feed - Camera View",
        attachImage: "Attach image",
        attachForAnalysis: "Attach image for analysis",
        removeImage: "Remove image",
        attachedPrefix: "Attached",
        sendMessage: "Send message",
        enterToSendHint: "Press Enter to send, Shift+Enter for a new line.",
        scrollToBottom: "Scroll to bottom",
        approveAndSend: "Approve & Send",
        cancelAction: "Cancel",
        roleOfficer: "Officer",
        profileLocation: "Main Gate",
        searchPlaceholder: "Search by Student ID, Camera, or Time...",
        online: "Online",
        signOut: "Sign out",
        sosLockdown: "SOS / LOCKDOWN",
        home: "Home",
        reports: "Reports",
        settings: "Settings",
        appTitle: "Campus Guard AI",
        appSubtitle: "Security Command Center",
        live: "LIVE",
        noGuardOnDuty: "All AI models are paused because no guard is currently on duty. Use \"Go on Duty\" to activate detection and notifications.",
        goOnDuty: "Go on Duty",
        goOffDuty: "Go Off Duty",
        noGuardIdentity: "No guard identity found. Please sign in again.",
        switchOnDutyFailed: "Failed to switch on duty.",
        switchOffDutyFailed: "Failed to switch off duty.",
        liveAlerts: "Live Alerts",
        activeCount: "{count} active",
        clearResolved: "Clear Resolved",
        reviewHint: "Review incidents, confirm threats, or mark false alarms.",
        reviewAlert: "Review Alert",
        confidence: "Confidence",
        location: "Location",
        detectedAt: "Detected At",
        classLabel: "Class",
        detected: "detected",
        capturedEvidence: "Captured evidence",
        confirmThreat: "Confirm Threat",
        falseAlarm: "False Alarm",
        noActiveAlerts: "No active alerts right now. New detections will appear here automatically.",
        confirm: "Confirm",
        allSystemsOperational: "All Systems Operational",
        capturedFrames: "Captured Frames:",
        mongoUsed: "MongoDB Used:",
        captureStorage: "Capture Images Storage:",
        threatConfirmedMsg: "Threat confirmed. Frame captured and stored. On-duty security guards have been notified.",
        falseAlarmRecordedMsg: "False alarm recorded. The result was stored in the database and saved locally in this browser.",
        serverUnavailable: "I couldn't reach the security server. Please try again.",
        emergency: "EMERGENCY",
        reportsTitle: "Security Intelligence Reports",
        reportsSubtitle: "Verified vs false-alarm analytics, guard performance, and trend intelligence.",
        totalAlerts: "Total Alerts",
        twoAngleVerifiedThreats: "Two-Angle Verified Threats",
        verifiedRate: "Verified Rate",
        falseAlarmRate: "False Alarm Rate",
        avgResponse: "Avg Response",
        verifiedVsFalseByType: "Verified vs False by Type",
        noTypeAnalytics: "No type analytics yet.",
        falseAlarmQuality: "False Alarm Quality",
        low: "Low",
        medium: "Medium",
        high: "High",
        topFalseAlarmGuards: "Top guards marking false alarms",
        noGuardData: "No guard data.",
        trendIntelligence: "Trend Intelligence",
        trendHourly: "Hourly",
        trendDaily: "Daily",
        trendWeekly: "Weekly",
        trendTotal: "Total",
        trendVerified: "Verified",
        trendFalse: "False",
        trendPending: "Pending",
        noTrendPoints: "No trend points yet.",
        guardSystemAnalysis: "Guard Working System Analysis",
        onDutyGuards: "On Duty Guards",
        offDutyGuards: "Off Duty Guards",
        guardName: "Guard Name",
        phone: "Phone",
        dutyStatus: "Duty Status",
        shifts: "Shifts",
        alertsHandled: "Alerts Handled",
        alertsPerHour: "Alerts / Hour",
        noGuardPerformance: "No guard performance data in selected period.",
        securityPersonnel: "Security Personnel",
        onDuty: "On Duty",
        offDuty: "Off Duty",
        verifiedEvidence: "Verified Evidence",
        noVerifiedEvidence: "No verified evidence available.",
        recentFalseAlarms: "Recent False Alarms",
        noFalseEvidence: "No false alarm evidence available.",
        refreshingReports: "Refreshing report analytics...",
        detectionPopupWeapon: "WEAPON DETECTED",
        detectionPopupViolence: "VIOLENCE DETECTED",
        detectionPopupFire: "FIRE DETECTED",
        detectionPopupSuspicious: "SUSPICIOUS ACTIVITY",
        detectionPopupDefault: "DETECTION ALERT",
        detectionArea: "Detection Area",
        frameId: "Frame ID",
        datasetReference: "Dataset Reference",
        time: "Time",
        captureStorageTitle: "Capture Storage",
        detectionLogged: "Detection logged and stored",
        dismissAlert: "Dismiss detection alert",
        guardNotifications: "Guard Notifications",
        confirmedThreatFeed: "Confirmed Threat Feed",
        guardIntro: "{name}, you will only receive alerts after administrator confirmation.",
        lastUpdated: "Last updated: {time}",
        refresh: "Refresh",
        switching: "Switching...",
        whatsappLanguage: "WhatsApp Language",
        whatsappLanguageHint: "OTP, confirmed threats, and admin instructions will follow this language.",
        save: "Save",
        saving: "Saving...",
        languageSavedGuard: "Language preference saved for WhatsApp alerts.",
        fetchNotificationsFailed: "Failed to fetch notifications.",
        missingGuardPhone: "Missing guard phone number. Please sign in again.",
        switchOnDutyGuardFailed: "Failed to switch on duty.",
        switchOffDutyGuardFailed: "Failed to switch off duty.",
        noConfirmedThreats: "No confirmed threats right now.",
        confirmed: "Confirmed",
        backToHome: "Back to Home",
        adminGuardManagement: "Admin Guard Management",
        adminGuardManagementHint: "Monitor and control on-duty and off-duty guard status",
        emailRequired: "Email is required",
        loginFailed: "Failed to log in",
        logoutFailed: "Failed to log out",
        duration: "Duration",
        threatsHandled: "Threats Handled",
        viewLiveAlerts: "View Live Alerts",
        noThreatsDetected: "No threats detected",
    },
    hi: {
        settingsTitle: "सेटिंग्स और नियंत्रण पैनल",
        securityConsole: "सुरक्षा कंसोल",
        settingsOverview: "सिस्टम व्यवहार, अलर्ट, भाषा और ऑपरेशन नीति प्रबंधित करें।",
        unsaved: "असहेजा",
        synced: "सिंक्ड",
        reset: "रीसेट",
        discardChanges: "परिवर्तन त्यागें",
        saveAll: "सभी सहेजें",
        unsavedChangesDetected: "असहेजे परिवर्तन मिले",
        allSettingsSynced: "सभी सेटिंग्स सिंक में हैं",
        sessionControl: "सेशन नियंत्रण",
        sessionControlHint: "साफ एडमिन संचालन के लिए साइन आउट केवल यहीं से नियंत्रित है।",
        whatsappGuardAlerts: "व्हाट्सऐप गार्ड अलर्ट",
        whatsappGuardAlertsDesc: "ड्यूटी पर मौजूद गार्ड के लिए व्हाट्सऐप अलर्ट डिलीवरी नियंत्रित करें।",
        aiPolicy: "एआई नीति",
        aiPolicyDesc: "स्थिर संचालन के लिए एआई संवेदनशीलता और डिस्पैच कूलडाउन समायोजित करें।",
        languageAndLocalization: "भाषा और स्थानीयकरण",
        languageAndLocalizationDesc: "पूरे प्लेटफॉर्म पर इंटरफेस और संदेश भाषा व्यवहार नियंत्रित करें।",
        dataAndMaintenance: "डेटा और मेंटेनेंस",
        dataMaintenanceAudit: "डेटा, मेंटेनेंस और ऑडिट",
        dataMaintenanceAuditDesc: "स्टोरेज वृद्धि, रिटेंशन नीति और महत्वपूर्ण ऑपरेशन लॉग देखें।",
        languageSectionTitle: "भाषा",
        languageSectionDescription: "डैशबोर्ड और चैट के लिए ऐप की भाषा चुनें।",
        languageLabel: "पसंदीदा भाषा",
        languageSaved: "भाषा अपडेट हो गई है। चैट और डैशबोर्ड आपकी चुनी हुई भाषा में दिखेंगे।",
        settingsSaved: "सेटिंग्स सहेजी गईं।",
        settingsSaveFailed: "सेटिंग्स सहेजने में विफल।",
        notificationsTitle: "सूचनाएं",
        notificationsDescription: "अलर्ट और सूचनाएं कैसे प्राप्त करें, यह चुनें",
        smsAlertsTitle: "एडमिन के लिए एसएमएस अलर्ट",
        smsAlertsDescription: "गंभीर खतरों के लिए टेक्स्ट संदेश भेजें",
        sirenTitle: "डिटेक्शन पर सायरन ध्वनि",
        sirenDescription: "खतरा मिलने पर अलर्ट ध्वनि चलाएं",
        emailAlertsTitle: "ईमेल सूचनाएं",
        emailAlertsDescription: "घटनाओं के ईमेल अपडेट प्राप्त करें",
        aiSensitivityTitle: "एआई संवेदनशीलता",
        aiSensitivityDescription: "डिटेक्शन सटीकता सीमा समायोजित करें",
        detectionThresholdLabel: "डिटेक्शन थ्रेशहोल्ड",
        moreAlerts: "ज्यादा अलर्ट",
        fewerAlerts: "कम अलर्ट",
        currentSettingLabel: "वर्तमान सेटिंग:",
        currentSettingDescription: "एआई केवल तभी अलर्ट ट्रिगर करेगा जब भरोसा {threshold}% या उससे अधिक हो। कम मान संवेदनशीलता बढ़ाएंगे, लेकिन गलत अलार्म बढ़ सकते हैं।",
        maintenanceTitle: "सिस्टम रखरखाव",
        maintenanceDescription: "स्टोरेज और सिस्टम सफाई प्रबंधित करें",
        clearFootageTitle: "पुरानी फुटेज साफ करें",
        clearFootageDescription: "30 दिन से पुरानी रिकॉर्डिंग हटाएं",
        clearNow: "अभी साफ करें",
        clearFootageWarning: "यह स्टोरेज खाली करने के लिए पुरानी फुटेज स्थायी रूप से हटा देगा। इस कार्रवाई को वापस नहीं लिया जा सकता।",
        cancel: "रद्द करें",
        saveSettingsBtn: "सेटिंग्स सहेजें और डिटेक्शन थ्रेशहोल्ड लागू करें",
        guardAssistant: "गार्डजीपीटी सहायक",
        commandCenter: "सुरक्षा कमांड सेंटर",
        askPlaceholder: "सुरक्षा कमांड या प्रश्न लिखें...",
        emptyChatHint: "पेंडिंग अलर्ट, नवीनतम अलर्ट, गार्ड काउंट पूछें या एआई विश्लेषण के लिए छवि अपलोड करें।",
        loadingSearch: "एक क्षण, मैं आपके लिए खोज रहा हूं...",
        loadingAnalyze: "कृपया प्रतीक्षा करें, डेटा विश्लेषित हो रहा है...",
        loadingFind: "ठीक है, मैं यह खोज रहा हूं...",
        loadingLogs: "सुरक्षा लॉग संसाधित हो रहे हैं...",
        dashboardFeed: "लाइव फीड - कैमरा दृश्य",
    },
    mr: {
        settingsTitle: "सेटिंग्ज आणि नियंत्रण पॅनेल",
        securityConsole: "सुरक्षा कन्सोल",
        settingsOverview: "सिस्टम वर्तन, अलर्ट, भाषा आणि ऑपरेशन धोरण व्यवस्थापित करा.",
        unsaved: "जतन न केलेले",
        synced: "समक्रमित",
        reset: "रीसेट",
        discardChanges: "बदल रद्द करा",
        saveAll: "सर्व जतन करा",
        unsavedChangesDetected: "जतन न केलेले बदल आढळले",
        allSettingsSynced: "सर्व सेटिंग्ज समक्रमित आहेत",
        sessionControl: "सेशन नियंत्रण",
        sessionControlHint: "स्वच्छ अॅडमिन ऑपरेशन्ससाठी साइन आउट फक्त इथेच व्यवस्थापित आहे.",
        whatsappGuardAlerts: "व्हॉट्सअॅप गार्ड अलर्ट",
        whatsappGuardAlertsDesc: "ड्युटीवरील गार्डसाठी व्हॉट्सअॅप अलर्ट वितरण नियंत्रित करा.",
        aiPolicy: "एआय धोरण",
        aiPolicyDesc: "स्थिर ऑपरेशन्ससाठी एआय संवेदनशीलता आणि डिस्पॅच कूलडाउन समायोजित करा.",
        languageAndLocalization: "भाषा आणि स्थानिकीकरण",
        languageAndLocalizationDesc: "संपूर्ण प्लॅटफॉर्मवर इंटरफेस आणि संदेश भाषेचे वर्तन नियंत्रित करा.",
        dataAndMaintenance: "डेटा आणि देखभाल",
        dataMaintenanceAudit: "डेटा, देखभाल आणि ऑडिट",
        dataMaintenanceAuditDesc: "स्टोरेज वाढ, रिटेन्शन धोरण आणि महत्त्वाचे ऑपरेशन लॉग पाहा.",
        languageSectionTitle: "भाषा",
        languageSectionDescription: "डॅशबोर्ड आणि चॅटसाठी अॅपची भाषा निवडा.",
        languageLabel: "प्राधान्य भाषा",
        languageSaved: "भाषा अद्ययावत झाली. चॅट आणि डॅशबोर्ड निवडलेल्या भाषेत दिसतील.",
        settingsSaved: "सेटिंग्ज जतन झाल्या.",
        settingsSaveFailed: "सेटिंग्ज जतन करण्यात अयशस्वी.",
        notificationsTitle: "सूचना",
        notificationsDescription: "अलर्ट आणि सूचना कशा मिळतील ते ठरवा",
        smsAlertsTitle: "अॅडमिनसाठी एसएमएस अलर्ट",
        smsAlertsDescription: "गंभीर धोक्यांसाठी संदेश पाठवा",
        sirenTitle: "डिटेक्शन झाल्यावर सायरन आवाज",
        sirenDescription: "धोका आढळल्यास अलर्ट आवाज वाजवा",
        emailAlertsTitle: "ईमेल सूचना",
        emailAlertsDescription: "घटनांचे ईमेल अपडेट मिळवा",
        aiSensitivityTitle: "एआय संवेदनशीलता",
        aiSensitivityDescription: "डिटेक्शन अचूकता मर्यादा बदला",
        detectionThresholdLabel: "डिटेक्शन थ्रेशहोल्ड",
        moreAlerts: "जास्त अलर्ट",
        fewerAlerts: "कमी अलर्ट",
        currentSettingLabel: "सध्याची सेटिंग:",
        currentSettingDescription: "एआय फक्त {threshold}% किंवा त्यापेक्षा जास्त खात्री असल्यास अलर्ट देईल. कमी मूल्ये संवेदनशीलता वाढवतील, पण चुकीचे अलार्म वाढू शकतात.",
        maintenanceTitle: "सिस्टम देखभाल",
        maintenanceDescription: "स्टोरेज आणि सिस्टम साफसफाई व्यवस्थापित करा",
        clearFootageTitle: "जुने फुटेज हटवा",
        clearFootageDescription: "30 दिवसांपेक्षा जुने रेकॉर्डिंग काढा",
        clearNow: "आत्ताच हटवा",
        clearFootageWarning: "यामुळे स्टोरेज मोकळी करण्यासाठी जुने फुटेज कायमचे हटवले जाईल. ही क्रिया मागे घेता येत नाही.",
        cancel: "रद्द करा",
        saveSettingsBtn: "सेटिंग्ज जतन करा आणि डिटेक्शन थ्रेशहोल्ड लागू करा",
        guardAssistant: "गार्डजीपीटी सहाय्यक",
        commandCenter: "सुरक्षा नियंत्रण कक्ष",
        askPlaceholder: "सुरक्षा आदेश किंवा प्रश्न लिहा...",
        emptyChatHint: "प्रलंबित अलर्ट, नवीन अलर्ट, गार्ड संख्या विचारा किंवा एआय विश्लेषणासाठी प्रतिमा अपलोड करा.",
        loadingSearch: "थोडा वेळ, मी तुमच्यासाठी शोधत आहे...",
        loadingAnalyze: "कृपया थांबा, माहितीचे विश्लेषण सुरू आहे...",
        loadingFind: "ठीक आहे, मी ते शोधत आहे...",
        loadingLogs: "सुरक्षा लॉग प्रक्रिया सुरू आहे...",
        dashboardFeed: "लाईव्ह फीड - कॅमेरा दृश्य",
        attachImage: "प्रतिमा जोडा",
        attachForAnalysis: "विश्लेषणासाठी प्रतिमा जोडा",
        removeImage: "प्रतिमा काढा",
        attachedPrefix: "जोडलेले",
        sendMessage: "संदेश पाठवा",
        enterToSendHint: "पाठवण्यासाठी Enter दाबा, नवीन ओळीसाठी Shift+Enter दाबा.",
        scrollToBottom: "खाली जा",
        approveAndSend: "मंजूर करून पाठवा",
        cancelAction: "रद्द करा",
        roleOfficer: "अधिकारी",
        profileLocation: "मुख्य प्रवेशद्वार",
        searchPlaceholder: "विद्यार्थी आयडी, कॅमेरा किंवा वेळ यानुसार शोधा...",
        online: "ऑनलाइन",
        signOut: "साइन आउट",
        sosLockdown: "एसओएस / लॉकडाउन",
        home: "मुख्यपृष्ठ",
        reports: "अहवाल",
        settings: "सेटिंग्ज",
        appTitle: "कॅम्पस गार्ड एआय",
        appSubtitle: "सुरक्षा नियंत्रण कक्ष",
        live: "थेट",
        noGuardOnDuty: "सध्या कोणताही गार्ड ड्युटीवर नसल्याने सर्व एआय मॉडेल थांबवले आहेत. डिटेक्शन आणि सूचना सुरू करण्यासाठी \"ड्युटी सुरू करा\" निवडा.",
        goOnDuty: "ड्युटी सुरू करा",
        goOffDuty: "ड्युटी समाप्त करा",
        noGuardIdentity: "गार्डची ओळख सापडली नाही. कृपया पुन्हा साइन इन करा.",
        switchOnDutyFailed: "ड्युटी सुरू करता आली नाही.",
        switchOffDutyFailed: "ड्युटी समाप्त करता आली नाही.",
        liveAlerts: "थेट अलर्ट",
        activeCount: "{count} सक्रिय",
        clearResolved: "निकाली अलर्ट साफ करा",
        reviewHint: "घटना तपासा, धोका पुष्टी करा किंवा खोटा अलार्म म्हणून नोंद करा.",
        reviewAlert: "अलर्ट तपासा",
        confidence: "विश्वासपातळी",
        location: "स्थान",
        detectedAt: "आढळल्याची वेळ",
        classLabel: "वर्ग",
        detected: "आढळले",
        capturedEvidence: "कॅप्चर केलेला पुरावा",
        confirmThreat: "धोका पुष्टी करा",
        falseAlarm: "खोटा अलार्म",
        noActiveAlerts: "सध्या कोणतेही सक्रिय अलर्ट नाहीत. नवीन डिटेक्शन येथे आपोआप दिसतील.",
        confirm: "पुष्टी",
        allSystemsOperational: "सर्व प्रणाली सुरळीत आहेत",
        capturedFrames: "कॅप्चर फ्रेम्स:",
        mongoUsed: "मोंगोDB वापर:",
        captureStorage: "कॅप्चर प्रतिमा संचयन:",
        threatConfirmedMsg: "धोका पुष्टी झाला. फ्रेम कॅप्चर करून जतन केली आहे. ड्युटीवरील सुरक्षा रक्षकांना कळवले आहे.",
        falseAlarmRecordedMsg: "खोटा अलार्म नोंदवला आहे. निकाल डेटाबेसमध्ये आणि या ब्राउझरमध्ये जतन केला आहे.",
        serverUnavailable: "सुरक्षा सर्व्हरशी संपर्क होऊ शकला नाही. कृपया पुन्हा प्रयत्न करा.",
        emergency: "आपत्कालीन स्थिती",
        reportsTitle: "सुरक्षा विश्लेषण अहवाल",
        reportsSubtitle: "पुष्ट विरुद्ध खोटा अलार्म विश्लेषण, गार्ड कामगिरी आणि ट्रेंड माहिती.",
        totalAlerts: "एकूण अलर्ट",
        twoAngleVerifiedThreats: "दोन-अँगल पडताळलेले धोके",
        verifiedRate: "पडताळणी दर",
        falseAlarmRate: "खोटा अलार्म दर",
        avgResponse: "सरासरी प्रतिसाद",
        verifiedVsFalseByType: "प्रकारानुसार पुष्ट विरुद्ध खोटे",
        noTypeAnalytics: "प्रकारानुसार विश्लेषण उपलब्ध नाही.",
        falseAlarmQuality: "खोट्या अलार्मची गुणवत्ता",
        low: "कमी",
        medium: "मध्यम",
        high: "उच्च",
        topFalseAlarmGuards: "खोटे अलार्म नोंदवणारे प्रमुख गार्ड",
        noGuardData: "गार्ड माहिती उपलब्ध नाही.",
        trendIntelligence: "ट्रेंड विश्लेषण",
        trendHourly: "तासानुसार",
        trendDaily: "दिवसानुसार",
        trendWeekly: "आठवड्यानुसार",
        trendTotal: "एकूण",
        trendVerified: "पडताळलेले",
        trendFalse: "खोटे",
        trendPending: "प्रलंबित",
        noTrendPoints: "ट्रेंड डेटा उपलब्ध नाही.",
        guardSystemAnalysis: "गार्ड कार्यप्रणाली विश्लेषण",
        onDutyGuards: "ड्युटीवरील गार्ड",
        offDutyGuards: "ड्युटीबाहेरील गार्ड",
        guardName: "गार्ड नाव",
        phone: "फोन",
        dutyStatus: "ड्युटी स्थिती",
        shifts: "शिफ्ट",
        alertsHandled: "हाताळलेले अलर्ट",
        alertsPerHour: "प्रति तास अलर्ट",
        noGuardPerformance: "निवडलेल्या कालावधीत गार्ड कामगिरी डेटा उपलब्ध नाही.",
        securityPersonnel: "सुरक्षा कर्मचारी",
        onDuty: "ड्युटीवर",
        offDuty: "ड्युटीबाहेर",
        verifiedEvidence: "पडताळलेले पुरावे",
        noVerifiedEvidence: "पडताळलेले पुरावे उपलब्ध नाहीत.",
        recentFalseAlarms: "अलिकडील खोटे अलार्म",
        noFalseEvidence: "खोट्या अलार्मचे पुरावे उपलब्ध नाहीत.",
        refreshingReports: "अहवाल विश्लेषण ताजे केले जात आहे...",
        detectionPopupWeapon: "शस्त्र आढळले",
        detectionPopupViolence: "हिंसाचार आढळला",
        detectionPopupFire: "आग आढळली",
        detectionPopupSuspicious: "संशयास्पद हालचाल",
        detectionPopupDefault: "डिटेक्शन अलर्ट",
        detectionArea: "डिटेक्शन क्षेत्र",
        frameId: "फ्रेम आयडी",
        datasetReference: "डेटासेट संदर्भ",
        time: "वेळ",
        captureStorageTitle: "कॅप्चर संचयन",
        detectionLogged: "डिटेक्शन नोंदवले आणि जतन केले",
        dismissAlert: "डिटेक्शन अलर्ट बंद करा",
        guardNotifications: "गार्ड सूचना",
        confirmedThreatFeed: "पुष्ट धोका फीड",
        guardIntro: "{name}, प्रशासक पुष्टी केल्यानंतरच तुम्हाला अलर्ट मिळतील.",
        lastUpdated: "शेवटचे अद्यतन: {time}",
        refresh: "ताजे करा",
        switching: "बदल सुरू आहे...",
        whatsappLanguage: "व्हॉट्सअॅप भाषा",
        whatsappLanguageHint: "ओटीपी, पुष्ट धोके आणि प्रशासक सूचना या भाषेत पाठवल्या जातील.",
        save: "जतन करा",
        saving: "जतन होत आहे...",
        languageSavedGuard: "व्हॉट्सअॅप अलर्टसाठी भाषा प्राधान्य जतन झाले.",
        fetchNotificationsFailed: "सूचना मिळवता आल्या नाहीत.",
        missingGuardPhone: "गार्डचा फोन क्रमांक उपलब्ध नाही. कृपया पुन्हा साइन इन करा.",
        switchOnDutyGuardFailed: "ड्युटी सुरू करण्यात अयशस्वी.",
        switchOffDutyGuardFailed: "ड्युटी समाप्त करण्यात अयशस्वी.",
        noConfirmedThreats: "सध्या कोणतेही पुष्ट धोके नाहीत.",
        confirmed: "पुष्टी",
        backToHome: "मुख्यपृष्ठावर जा",
        adminGuardManagement: "प्रशासक गार्ड व्यवस्थापन",
        adminGuardManagementHint: "ड्युटीवरील आणि ड्युटीबाहेरील गार्ड स्थितीवर नियंत्रण ठेवा",
        emailRequired: "ईमेल आवश्यक आहे",
        loginFailed: "लॉग इन अयशस्वी",
        logoutFailed: "लॉग आउट अयशस्वी",
        duration: "कालावधी",
        threatsHandled: "हाताळलेले धोके",
        viewLiveAlerts: "थेट अलर्ट पहा",
        noThreatsDetected: "कोणतेही धोके आढळले नाहीत",
    },
};

const TYPE_LABELS: Record<AppLanguage, Record<string, string>> = {
    en: {
        weapon: "Weapon",
        violence: "Violence",
        fire: "Fire",
        suspicious: "Suspicious Activity",
        anomaly: "Suspicious Activity",
        pistol: "Pistol",
        long_knife: "Long Knife",
        pocket_knife: "Pocket Knife",
    },
    hi: {
        weapon: "हथियार",
        violence: "हिंसा",
        fire: "आग",
        suspicious: "संदिग्ध गतिविधि",
        anomaly: "संदिग्ध गतिविधि",
        pistol: "पिस्तौल",
        long_knife: "लंबी छुरी",
        pocket_knife: "फोल्डिंग छुरी",
    },
    mr: {
        weapon: "शस्त्र",
        violence: "हिंसाचार",
        fire: "आग",
        suspicious: "संशयास्पद हालचाल",
        anomaly: "संशयास्पद हालचाल",
        pistol: "पिस्तूल",
        long_knife: "लांब चाकू",
        pocket_knife: "खिसेतील चाकू",
    },
};

const STATUS_LABELS: Record<AppLanguage, Record<string, string>> = {
    en: { pending: "Pending", confirmed: "Confirmed", dismissed: "Dismissed", resolved: "Resolved" },
    hi: { pending: "लंबित", confirmed: "पुष्ट", dismissed: "खारिज", resolved: "समाधान" },
    mr: { pending: "प्रलंबित", confirmed: "पुष्टी", dismissed: "रद्द", resolved: "निकाली" },
};

export function tf(language: string, key: string, vars: Record<string, string | number>): string {
    let text = t(language, key);
    Object.entries(vars).forEach(([k, v]) => {
        text = text.replaceAll(`{${k}}`, String(v));
    });
    return text;
}

export function typeLabel(language: string, value?: string | null): string {
    const normalizedLanguage = normalizeLanguage(language);
    const normalized = String(value || "").trim().toLowerCase().replace(/\s+/g, "_");
    if (!normalized) return "";
    return TYPE_LABELS[normalizedLanguage][normalized] || TYPE_LABELS.en[normalized] || value || "";
}

export function statusLabel(language: string, value?: string | null): string {
    const normalizedLanguage = normalizeLanguage(language);
    const normalized = String(value || "").trim().toLowerCase();
    if (!normalized) return "";
    return STATUS_LABELS[normalizedLanguage][normalized] || STATUS_LABELS.en[normalized] || value || "";
}

export function t(language: string, key: string): string {
    const normalized = normalizeLanguage(language);
    return DICTIONARY[normalized]?.[key] || DICTIONARY.en[key] || key;
}
